[package]
name = "yousui"
version = "0.0.1"
published-at = "0x8a109f80e3695c56ecaaf634bcf573d6fd6ad4f5893a7c11783baf7187e9841c"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet" }
YOUSUINFTS = { local = "../yousui_free_minting_sc" }
yousui_staking = { local = "../staking" }

[addresses]
yousui =  "0x0"
sui =  "0x2"

#mainnet
yousuinfts = "0x6a29b3b80de2bd69ee94b2a2f11e5bf2e3614d1cc08f1cb16eefa290bc859cb0"
yousui_staking = "0x0f0cdf14bcac51ef9f468600807f4224c97bc21e4480b34a9cfd51eeae63b297"